# Generated by Django 3.2 on 2022-10-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categories_posts_categrories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='categrories',
        ),
    ]
