# Generated by Django 3.2 on 2022-10-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posts_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
