# Generated by Django 3.2 on 2022-10-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20221019_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='updated_by',
            new_name='last_modified_by',
        ),
    ]
