# Generated by Django 3.2 on 2022-10-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221019_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
